
version: '3.8'

services:
  mongodb:
    image: mongo:4.4
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret
    volumes:
      - mongo-data:/data/db
    networks:
      - my-ntw

  backend:
    build:
      context: ./backend
    container_name: my-backend
    restart: always
    expose:
      - "8000"
    environment:
      - MONGO_URI=mongodb://admin:secret@mongodb:27017/todo-app?authSource=admin
      - PORT=8000
    depends_on:
      - mongodb
    networks:
      - my-ntw

  frontend:
    build:
      context: ./frontend
    container_name: my-frontend
    restart: always
    expose:
      - "3000"
    depends_on:
      - backend
    networks:
      - my-ntw
    environment:
      - REACT_APP_API_URL=/api

  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - backend
    networks:
      - my-ntw   #custom-network

volumes:
  mongo-data:

networks:
  my-ntw:
    driver: bridge

