
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: mern-todo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: akshaykumar0007/mern-todo-back:19
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: backend-config
            - secretRef:
                name: backend-secret

