
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: mern-todo
spec:
  selector:
    app: frontend
  ports:
    - port: 80
      targetPort: 80
  type: LoadBalancer
  loadBalancerIP: 192.168.1.240

