
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: mern-todo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: akshaykumar0007/mern-todo-front:40
          ports:
            - containerPort: 80

