---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mongo-secret
  namespace: mern-todo
spec:
  encryptedData:
    MONGO_INITDB_ROOT_PASSWORD: AgAqfF13WeJWPJOgwvLTcdgPYh8jAjtpNSIfhZ8iG4xdAxQHBoJx7eOVLl0Mka0w+qO/ey39HA0yPW3QGqIJMR0aNZ3advm/4S2E2Xoa2QPwsZUv8TUt3W2PApBm3IMyu4/+aEVxSrTORzsk06P3MW1m+NZ1/pJfSwEihFzoRvAdNCKT3HgN+1yfLmRLdvsKidqiSmjIDtJ5c9pxxLHkwP9/x1BwdMVvBxbohlAP/thy3Bwo0ib0SicCCEf5Kgau6GQSKolo4MbPP9Ujg7X1NjAG0pochswRZEvZvbodbQzOGXDRuBl8p7xAavwKQ6dIIIaWaccunvk0pzY6ZIPNEapNiS3rf4ke/jE5a0fY2fjxtML/9EAS3Plx5wZrUUQFHkS5GInZ2yhquWdkzZJsfXDupysE90x5ylJlWsoF7zoY1iSn0vJIfm1YChubJbiouDRur4/4breQ10Sz59IriSlQoz5weTV8wV0k1ZSTlm+/mftUqIkQoaRFDFExVMIVkzWOC5zo5NXQOfD+ZDwII1gI70P87rOx20JrVMhJWdPoyHP+wQnuFGStOQ5OlNT6uN3YNlFK4gG9Stq3XbTsnoiK1WTKv2tL7lXZZylRlG0semrT8Z3hFq2gcCCPo5xK6Ggeo2seNDAJKLAPPgpyEQneE2V1sD0dhNpQHBWUgN7bZzIXhKVuxD7gSUMBmTp3O9Ux1lFfU6Q=
    MONGO_INITDB_ROOT_USERNAME: AgAiLmQ7/+9pBzy+sirgcKEtJk0GMxuh1Cr+eRNja5/u5+5w8qIZmC5VUmV3AtvBWM9hFr4smIBI+Xth7GMuKOd2JpHB0/f76rYD7Do3ojKpgO2XhB7gPVw2Klu9FRU7bxU6dmJx2a0GiPOTLOuVnC1AmCATXBoFO3tFFmmHcBMpTiOIswCtgBDOrZzesJw6hI+G4QZyIspJca846a2VYm3o24bEaJ3jm+93EaCzc6Rt3jNPQcDDLR85MmDl6V55kzd5OclYdg2wI2RgysfT+1chzjF/MCbQvWU1lo39nvF+aEirEbgt8tum69mEpakn1uUJorhMhgFU5rZDV8n0yGPOpAvdlL0wWRZVwUYMGq9mi7UPiaqs/dkuqEgSgwoBFfobxt0DIupS0ZuPWRyvi57QOEnJ32oNsDA/mypn/xuOC6EGp+s3XIT2Td0aBdupMZOksrWfNLXD/hzpsULzId5srlkfsnJwIrOLqsSFmAHGFXK8DPjilYGRK5V9va6Z1zYfVg9nd6bwowAFkB5zA0xhYrK7/neBze9hgGrCT3QLUS3paljfEO9XbzaobVuKB34SG6//9P/N9eLlBDihAGunTY7cvOXvZj5VsYwl/30tbBwS6uK1uLFh/6UhenBNgSxagE7DpHe10nmnWlKceXdr1JdHRMkTD7Cvy3gBy57pfRgbqyEK1TdSixoUhPiCk5gDi9rwug==
  template:
    metadata:
      creationTimestamp: null
      name: mongo-secret
      namespace: mern-todo
    type: Opaque
